# Generated by Django 6.0 on 2026-01-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='ReportBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('bug_type', models.CharField(choices=[('UI/UX', 'User Interface'), ('Functional', 'Functional'), ('Performance', 'Performance'), ('Security', 'Security'), ('Compatibility', 'Compatibility'), ('Accessibility', 'Accessibility'), ('Network', 'Network'), ('Database', 'Database'), ('Integration', 'Integration'), ('Other', 'Other')], max_length=50)),
                ('bug_other', models.CharField(blank=True, max_length=100)),
                ('issue', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='web_portal/bug_report/images')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Report Bug',
                'verbose_name_plural': 'Report Bugs',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='web_portal/service/images')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
