# Generated by Django 6.0 on 2025-12-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorregistration',
            options={'verbose_name': 'Profile Migration', 'verbose_name_plural': 'Profile Migrations'},
        ),
    ]
