# Generated by Django 6.0 on 2026-01-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_operations', '0002_alter_doctorregistration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorregistration',
            options={'verbose_name': 'Profile Migration Application', 'verbose_name_plural': 'Profile Migrations Applications'},
        ),
    ]
