# Generated by Django 6.0 on 2025-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
