# Generated by Django 6.0 on 2025-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_height_alter_patient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='weight in kg', max_digits=7, null=True),
        ),
    ]
