# Generated by Django 6.0 on 2025-12-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0004_alter_patient_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('title', models.CharField(help_text='3-4 word summary of your issue', max_length=100)),
                ('symptoms', models.TextField(help_text='Describe the symptoms or reason for consultation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('meeting_date', models.DateField(help_text='Meeting date')),
                ('meeting_link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.availabletime')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='appointment/patient/symptom_img/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appointments.appointments')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
